name: delivery_kris
description: A new Flutter project.

publish_to: 'https://github.com/search?q=delivery_kris' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"



vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs


dependencies:
  flutter:
    sdk: flutter
  responsive_framework: ^0.2.0
  device_preview: ^1.1.0
  flutter_svg: ^1.1.5
  flutter_screenutil: ^5.0.0+2
  json_annotation: ^4.0.1
  json_serializable: ^6.0.1
  dio: ^4.0.0
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  flutter_modular: ^5.0.3
  bot_toast: ^4.0.1
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.1.0
  flutter_launcher_icons: "^0.10.0"
  cupertino_icons: ^1.0.2
  audioplayers: ^1.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/app_icon.png"
  Android: true
  # optionally, as transparency is not allowed on app store
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  modular_codegen: ^3.0.0
  mobx_codegen: ^2.0.1+3
  build_runner: 

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/img/
    - assets/json/
    - assets/audio/
