// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0X5uZJF1HKC6bPURWADplFb9YIk_wjAc',
    appId: '1:823874873915:web:5c5dc67b7f261082e88a1e',
    messagingSenderId: '823874873915',
    projectId: 'delivery-kris',
    authDomain: 'delivery-kris.firebaseapp.com',
    storageBucket: 'delivery-kris.appspot.com',
    measurementId: 'G-TFQ0S3C39L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBftBGt28_Sy9Qa9zKbyJHbkNKfGDXs9Vc',
    appId: '1:823874873915:android:b966e67edb6bd45ee88a1e',
    messagingSenderId: '823874873915',
    projectId: 'delivery-kris',
    storageBucket: 'delivery-kris.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAEv-nnDKShA45vPy2mtLa5_EvT3kFKIE',
    appId: '1:823874873915:ios:c54f1e98b0bedda2e88a1e',
    messagingSenderId: '823874873915',
    projectId: 'delivery-kris',
    storageBucket: 'delivery-kris.appspot.com',
    iosClientId: '823874873915-dstqlhica0nijuubvfu6opf10dr7p208.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryKris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAEv-nnDKShA45vPy2mtLa5_EvT3kFKIE',
    appId: '1:823874873915:ios:c54f1e98b0bedda2e88a1e',
    messagingSenderId: '823874873915',
    projectId: 'delivery-kris',
    storageBucket: 'delivery-kris.appspot.com',
    iosClientId: '823874873915-dstqlhica0nijuubvfu6opf10dr7p208.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryKris',
  );
}
